version: '3'

services:
  films-server:
    image: films-server:1.0
    container_name: graphql-server
    ports: 
      - 8080:8080
    # environment:
    #   - MONGODB_URI=mongodb+srv://SMPlay:WOuCyMZE02TSYYqE@cluster0-cdsg8.mongodb.net/films-search?retryWrites=true&w=majority
    #   - BASE_URL=http://192.168.99.100:8080/
    #   - NODE_ENV=production
    networks:
      - films-network

  films-ui:
    image: films:1.0
    container_name: react-ui
    ports:
      - 8081:8081
    links:
      - films-server
    env_file:
      - web-variables.env
    # environment:
    #   - REACT_APP_API_HOST=$REACT_APP_API_HOST
    networks:
      - films-network

networks:
  films-network:
