version: '3'

services:
  films-server:
    image: films-server:1.0
    container_name: films-server
    ports:
      - 8080:8080
    environment:
      - MONGODB_URI="mongodb+srv://SMPlay:WOuCyMZE02TSYYqE@cluster0-cdsg8.mongodb.net/films-search?retryWrites=true&w=majority"
      - NODE_ENV=production
    networks:
      - films-network

  films-ui:
    image: films-ui:1.0
    container_name: films-ui
    ports:
      - 8081:8081
    links:
      - films-server
    # environment:
    #   - REACT_APP_API_HOST=pipka
    networks:
      - films-network

networks:
  films-network: